version: '3'
services:
  ubuntu-ansible:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
       - "2222:22"
    networks:
      ansible_network:
        ipv4_address: 10.5.0.9
networks:
  ansible_network:
    driver: bridge
    name: ansible_network
    ipam:
      config:
        - subnet: 10.5.0.0/16